-- AlterTable
ALTER TABLE "Card" ADD COLUMN     "boardId" INTEGER NOT NULL DEFAULT 1;

-- AddForeignKey
ALTER TABLE "Card" ADD CONSTRAINT "Card_boardId_fkey" FOREIGN KEY ("boardId") REFERENCES "Board"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
